/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 car.glb --transform --keepmeshes
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Mycar(props) {
  const { nodes, materials } = useGLTF("/car-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          geometry={nodes.Mesh_17_1.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Mesh_17_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Mesh_17_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Mesh_17_4.geometry}
          material={materials.Material_8}
        />
        <mesh
          geometry={nodes.Mesh_17_5.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Mesh_17_6.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Mesh_17_7.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Mesh_17_8.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Mesh_17_9.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Mesh_17_10.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Mesh_17_11.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Mesh_17_12.geometry}
          material={materials["Black Material.001"]}
        />
      </group>
      <mesh
        geometry={nodes.Mesh_17001.geometry}
        material={materials["Glass file"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/car-transformed.glb");
